library font_awesome_flutter;

import 'package:flutter/widgets.dart';
import 'package:font_awesome_flutter/src/icon_data.dart';
export 'package:font_awesome_flutter/src/fa_icon.dart';
export 'package:font_awesome_flutter/src/icon_data.dart';
export 'package:font_awesome_flutter/src/fa_duotone_icon.dart';

// THIS FILE IS AUTOMATICALLY GENERATED!

/// Icons based on font awesome 5.15.1
class FontAwesomeIcons {

}